apiVersion: v1
kind: ReplicationController
metadata:
  name: my-custom-app-rct
spec:
  replicas: 3
  selector:
    app: my-custom-app-rct
  template:
    metadata:
      name: my-custom-app-rct
      labels:
        app: my-custom-app-rct
    spec:
      containers:
      - name: my-custom-app-rct
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo running > index.html && python -m http.server 8080']
        ports:
        - containerPort: 8080