kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
    - name: myfrontend
      image: nginx:1.15.12
  nodeSelector:
    "beta.kubernetes.io/os": linux

#https://docs.microsoft.com/es-es/azure/aks/operator-best-practices-advanced-scheduler