apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
  - name: my-container2
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod3
spec:
  containers:
  - name: my-container3
    image: nginx:alpine